--------------------------------------------------------
--  파일이 생성됨 - 화요일-1월-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRADE_LIST
--------------------------------------------------------

  CREATE TABLE "BANG"."GRADE_LIST" 
   (	"GRADE" NUMBER, 
	"GRADE_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BANG.GRADE_LIST
SET DEFINE OFF;
Insert into BANG.GRADE_LIST (GRADE,GRADE_NAME) values (0,'master');
Insert into BANG.GRADE_LIST (GRADE,GRADE_NAME) values (1,'bronze');
Insert into BANG.GRADE_LIST (GRADE,GRADE_NAME) values (2,'silver');
Insert into BANG.GRADE_LIST (GRADE,GRADE_NAME) values (3,'gold');
Insert into BANG.GRADE_LIST (GRADE,GRADE_NAME) values (4,'vip');
Insert into BANG.GRADE_LIST (GRADE,GRADE_NAME) values (5,'vvip');
--------------------------------------------------------
--  DDL for Index SYS_C007218
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANG"."SYS_C007218" ON "BANG"."GRADE_LIST" ("GRADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GRADE_LIST
--------------------------------------------------------

  ALTER TABLE "BANG"."GRADE_LIST" ADD PRIMARY KEY ("GRADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
