UPDATE MEMBER SET pass='1', name='1', age=1 WHERE id='haha';

ALTER TABLE MEMBER ADD grade NUMBER DEFAULT 1;

SELECT * FROM MEMBER;

DROP TABLE GRADE_LIST;
CREATE TABLE GRADE_LIST (
	grade NUMBER PRIMARY KEY,
	grade_name VARCHAR2(30 BYTE)
);

INSERT INTO GRADE_LIST VALUES(0,'MASTER');
INSERT INTO GRADE_LIST VALUES(1,'BRONZE');
INSERT INTO GRADE_LIST VALUES(2,'SILVER');
INSERT INTO GRADE_LIST VALUES(3,'GOLD');
INSERT INTO GRADE_LIST VALUES(4,'VIP');
INSERT INTO GRADE_LIST VALUES(5,'VVIP');

SELECT grade FROM grade_list WHERE grade_name = 'bronze';

DELETE FROM MEMBER WHERE name LIKE '%1111111111';
